services:
  postgres:
    image: postgres:17.9@sha256:7ad98329d513dd497293b951c195ca354274a77f12ddbbbbf85e68a811823d72
    environment:
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres_socket:/var/run/postgresql
