name: File Review

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

permissions:
  contents: read

jobs:
  analyze:
    uses: ./.github/workflows/ci-markdown-checks.yml
  filesystem:
    uses: ./.github/workflows/file_review-filesystem.yml
